# Generated by Django 4.2.1 on 2023-10-24 15:18

import core.untils.cinema_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seo',
            name='keywords_seo',
            field=models.CharField(blank=True, help_text='Input keywords SEO', max_length=400, null=True, validators=[core.untils.cinema_validator.SeoValidator.validate_keywords]),
        ),
    ]
