# Generated by Django 4.2.1 on 2023-06-05 11:13

import core.untils.custom_user_validator
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(blank=True, default=datetime.datetime.now, help_text='Select day birthday', null=True, validators=[core.untils.custom_user_validator.UserValidator.birthday_validator]),
        ),
    ]
